# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uart_tool.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 121, 191))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 31, 38, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(41, 30, 76, 152))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_uart = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_uart.setObjectName("comboBox_uart")
        self.verticalLayout_2.addWidget(self.comboBox_uart)
        self.comboBox_baud = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.comboBox_baud.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_baud)
        self.comboBox_databit = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_databit.setObjectName("comboBox_databit")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.comboBox_databit.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_databit)
        self.comboBox_polarity = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_polarity.setObjectName("comboBox_polarity")
        self.comboBox_polarity.addItem("")
        self.comboBox_polarity.addItem("")
        self.comboBox_polarity.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_polarity)
        self.comboBox_stopbit = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_stopbit.setObjectName("comboBox_stopbit")
        self.comboBox_stopbit.addItem("")
        self.comboBox_stopbit.addItem("")
        self.comboBox_stopbit.addItem("")
        self.comboBox_stopbit.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_stopbit)
        self.comboBox_flow = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_flow.setObjectName("comboBox_flow")
        self.comboBox_flow.addItem("")
        self.comboBox_flow.addItem("")
        self.comboBox_flow.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_flow)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 200, 131, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_recvascii = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_recvascii.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.radioButton_recvascii.setObjectName("radioButton_recvascii")
        self.radioButton_recvhex = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_recvhex.setGeometry(QtCore.QRect(80, 20, 51, 16))
        self.radioButton_recvhex.setObjectName("radioButton_recvhex")
        self.checkBox_autoline = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_autoline.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.checkBox_autoline.setObjectName("checkBox_autoline")
        self.checkBox_showsend = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_showsend.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.checkBox_showsend.setObjectName("checkBox_showsend")
        self.checkBox_showtime = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_showtime.setGeometry(QtCore.QRect(20, 80, 71, 16))
        self.checkBox_showtime.setObjectName("checkBox_showtime")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 310, 131, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_sendascii = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_sendascii.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.radioButton_sendascii.setObjectName("radioButton_sendascii")
        self.radioButton_sendhex = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_sendhex.setGeometry(QtCore.QRect(80, 20, 51, 16))
        self.radioButton_sendhex.setObjectName("radioButton_sendhex")
        self.checkBox_repeatsend = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_repeatsend.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.checkBox_repeatsend.setObjectName("checkBox_repeatsend")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(90, 70, 41, 21))
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(10, 70, 71, 22))
        self.spinBox.setObjectName("spinBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(140, 10, 331, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit_get = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_get.setGeometry(QtCore.QRect(140, 320, 251, 51))
        self.textEdit_get.setObjectName("textEdit_get")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(400, 340, 71, 23))
        self.btn_send.setObjectName("btn_send")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionstart = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ico/正常播放(Play Normal)-ico_爱给网_aigei_com (1).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionstart.setIcon(icon)
        self.actionstart.setObjectName("actionstart")
        self.actionpause = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ico/暂停已按下(Pause Pressed)-ico_爱给网_aigei_com.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionpause.setIcon(icon1)
        self.actionpause.setObjectName("actionpause")
        self.actionstop = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ico/停止正常红色(Stop Normal Red)-ico_爱给网_aigei_com.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionstop.setIcon(icon2)
        self.actionstop.setObjectName("actionstop")
        self.actionqingsao = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ico/清扫_爱给网_aigei_com.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionqingsao.setIcon(icon3)
        self.actionqingsao.setObjectName("actionqingsao")
        self.menu.addAction(self.actionstart)
        self.menu.addAction(self.actionpause)
        self.menu.addAction(self.actionstop)
        self.menu.addAction(self.actionqingsao)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.actionstart)
        self.toolBar.addAction(self.actionpause)
        self.toolBar.addAction(self.actionstop)
        self.toolBar.addAction(self.actionqingsao)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "串口设置"))
        self.label.setText(_translate("MainWindow", "串口"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.label_3.setText(_translate("MainWindow", "数据位"))
        self.label_4.setText(_translate("MainWindow", "校验位"))
        self.label_5.setText(_translate("MainWindow", "停止位"))
        self.label_6.setText(_translate("MainWindow", "流控"))
        self.comboBox_baud.setItemText(0, _translate("MainWindow", "2400"))
        self.comboBox_baud.setItemText(1, _translate("MainWindow", "4800"))
        self.comboBox_baud.setItemText(2, _translate("MainWindow", "9600"))
        self.comboBox_baud.setItemText(3, _translate("MainWindow", "19200"))
        self.comboBox_baud.setItemText(4, _translate("MainWindow", "38400"))
        self.comboBox_baud.setItemText(5, _translate("MainWindow", "57600"))
        self.comboBox_baud.setItemText(6, _translate("MainWindow", "115200"))
        self.comboBox_baud.setItemText(7, _translate("MainWindow", "128000"))
        self.comboBox_baud.setItemText(8, _translate("MainWindow", "256000"))
        self.comboBox_databit.setItemText(0, _translate("MainWindow", "5"))
        self.comboBox_databit.setItemText(1, _translate("MainWindow", "6"))
        self.comboBox_databit.setItemText(2, _translate("MainWindow", "7"))
        self.comboBox_databit.setItemText(3, _translate("MainWindow", "8"))
        self.comboBox_polarity.setItemText(0, _translate("MainWindow", "无"))
        self.comboBox_polarity.setItemText(1, _translate("MainWindow", "奇校验"))
        self.comboBox_polarity.setItemText(2, _translate("MainWindow", "偶校验"))
        self.comboBox_stopbit.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_stopbit.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_stopbit.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_stopbit.setItemText(3, _translate("MainWindow", "2.5"))
        self.comboBox_flow.setItemText(0, _translate("MainWindow", "无"))
        self.comboBox_flow.setItemText(1, _translate("MainWindow", "CTS/RTS"))
        self.comboBox_flow.setItemText(2, _translate("MainWindow", "XON/XOFF"))
        self.groupBox_2.setTitle(_translate("MainWindow", "接收设置"))
        self.radioButton_recvascii.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_recvhex.setText(_translate("MainWindow", "HEX"))
        self.checkBox_autoline.setText(_translate("MainWindow", "自动化行"))
        self.checkBox_showsend.setText(_translate("MainWindow", "显示发送"))
        self.checkBox_showtime.setText(_translate("MainWindow", "显示时间"))
        self.groupBox_3.setTitle(_translate("MainWindow", "发送设置"))
        self.radioButton_sendascii.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_sendhex.setText(_translate("MainWindow", "HEX"))
        self.checkBox_repeatsend.setText(_translate("MainWindow", "重复发送"))
        self.label_7.setText(_translate("MainWindow", "毫秒/次"))
        self.btn_send.setText(_translate("MainWindow", "发送"))
        self.menu.setTitle(_translate("MainWindow", "编辑"))
        self.menu_2.setTitle(_translate("MainWindow", "显示"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionstart.setText(_translate("MainWindow", "开始"))
        self.actionpause.setText(_translate("MainWindow", "暂停"))
        self.actionpause.setToolTip(_translate("MainWindow", "pauser"))
        self.actionstop.setText(_translate("MainWindow", "停止"))
        self.actionqingsao.setText(_translate("MainWindow", "清扫"))
